---
- name: copy settings.json to host
  copy:
    src: settings.json
    dest: /home/ubuntu/application-settings.json

- name: copy replicated.conf to host
  copy:
    src: replicated.conf
    dest: /etc/replicated.conf 

 - name: copy licence file
   copy:
     src: license.rli
     dest: /home/ubuntu/license.rli

- name: Download Terraform Enterprise Installer
  get_url:
    url: https://install.terraform.io/ptfe/stable
    dest: /home/ubuntu/install.sh
    mode: 0700

- name: run pTFE install
  shell: bash ./install.sh no-proxy private-address={{ ansible_eth0.ipv4.address }} public-address={{ hostvars[item].ansible_host }}
  args:
    chdir: /home/ubuntu/
  with_items: "{{ groups.all }}"


